// <auto-generated />
using System;
using BankingSystem.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingSystem.DataBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankingSystem.DataBase.Models.AccountType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("824e7549-8bf7-4454-900a-ef48303b184c"),
                            Name = "Liability"
                        },
                        new
                        {
                            Id = new Guid("31d71cdc-bd13-4595-9115-767801d7cada"),
                            Name = "Asset"
                        });
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AccountType_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountType_FK");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankAccountPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankTransationId_FK")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BankTransationId_FK");

                    b.ToTable("BankAccountPostings");
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<Guid>("BankAccount_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaymentMethod_FK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BankAccount_FK");

                    b.HasIndex("PaymentMethod_FK");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65e31bdf-12d2-478a-b8e8-f4e4f02013d1"),
                            Name = "Cash"
                        },
                        new
                        {
                            Id = new Guid("7ffe1622-ee29-424b-a248-942938b993dc"),
                            Name = "Cheque"
                        },
                        new
                        {
                            Id = new Guid("f3d2e807-c5ad-4b65-bae0-8de2fc05528b"),
                            Name = "NEFT"
                        },
                        new
                        {
                            Id = new Guid("dcc1a001-98a3-47e1-8256-f1b4fa9206e6"),
                            Name = "RTGS"
                        },
                        new
                        {
                            Id = new Guid("f6dcba8a-89d5-401a-b4be-34fd5b38f49a"),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankAccount", b =>
                {
                    b.HasOne("BankingSystem.DataBase.Models.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("AccountType_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankAccountPosting", b =>
                {
                    b.HasOne("BankingSystem.DataBase.Models.BankTransaction", "BankTransaction")
                        .WithMany()
                        .HasForeignKey("BankTransationId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankTransaction");
                });

            modelBuilder.Entity("BankingSystem.DataBase.Models.BankTransaction", b =>
                {
                    b.HasOne("BankingSystem.DataBase.Models.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccount_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankingSystem.DataBase.Models.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethod_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");

                    b.Navigation("PaymentMethod");
                });
#pragma warning restore 612, 618
        }
    }
}
